# Generated by Django 5.0.4 on 2024-04-29 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['complete', '-created']},
        ),
        migrations.RenameField(
            model_name='todoitem',
            old_name='date',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='content',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='decription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='title',
            field=models.CharField(default='New Task', max_length=250),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
