# Generated by Django 5.0.4 on 2024-04-29 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todoitem_options_rename_date_todoitem_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='decription',
            new_name='description',
        ),
    ]
